#' Fast Fourier Transform
#'
#' Fast Fourier Transform (FFT) that gets sample representation of
#' polynomials from their coefficient representations. This is an
#' efficient iterative FFT implementation as described on page 917 of
#' the book "Introduction to Algorithms" 3rd edition by Thomas Cormen
#' et al.
#' @param a A vector of polynomial coefficients from the smallest to the
#' highest power. That is, a=(a_0,a_1, ..., a_n-1).
#' @export

fft = function(a) {

  n = length(a)
  # get a into the desired order using bit_reverse
  A = bit_reverse(a)
  for (s in 1:log2(n)) {

    m = 2 ^ s
    # the principle m-th root of unity
    # the other m-th roots of unity can be generated by taking
    # integer powers of the principle root
    omegaM = complex(real = cos(2 * pi / m), imaginary = sin(2 * pi / m))
    for (k in seq(1, n, m)) {

      omega = 1
      for (j in 1:(m / 2)) {

        t = omega * A[k + j - 1 + m / 2]
        u = A[k + j - 1]
        A[k + j - 1] = u + t
        A[k + j - 1 + m / 2] = u - t
        omega = omega * omegaM

      }

    }

  }

  return(A)

}
